dataset:
  name: pomegranate_growth_stage
  image_size: 640
  num_classes: 3

  # 🔥 Kaggle dataset root (THIS IS THE KEY FIX)
  kaggle_root: /kaggle/input/pomegranate-dataset/pomegranate_dataset/yolo

  yolo:
    images: images
    labels: labels

  classes:
    - immature
    - mature
    - overripe


training:
  epochs: 30
  batch_size: 16
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
